### ISSUE TITLE
not working on android device tried a lot

### ISSUE THREAD

**Issue by nadeemkhan** [mhartington/ionic-firebase-auth#1]
it's working on web browser but when i tested it on android device nothing happened on fb tw click.
i'm using this command ionic run android to run on my device.

here is some details
OS - X Yosemite ( V - 10.10.4 )
Mobile - Moto G 1st Gen ( V - 5.0.2 )
Android Studio - 1.2.2

thanks.

**Comment by mhartington** [comment]
Do you have the Cordova whitelist plugin installed?

Mike Hartington

**Comment by nadeemkhan** [comment]
Thanks for reply now it's working. :-)
