### ISSUE TITLE
Firebase $authWithOAuthRedirect doesn't call $onAuth without page refresh

### ISSUE THREAD

**Issue by Hitman666** [mhartington/ionic-firebase-auth#2]
I actually posted the question on StackOverflow and Ionic forums (even the slack channel) but no one replied so far: http://stackoverflow.com/questions/31872935/firebase-authwithoauthredirect-doesnt-call-onauth-without-page-refresh.

So, even in this example, when I successfully login with Twitter, nothing happens. I stay at the dashboard tab. However, if I refresh the page (F5) I properly see my Twitter handle and image.

So, please can you share some knowledge on this? As you can see in the SO question, I managed to "work around it" by setting the auth in $timeout, but only with 3 seconds. Besides, this isn't a viable solution, and there must "be a better way", so please suggest.

**Comment by mhartington** [comment]
This only happens in the browser using `$authWithOAuthRedirect`. This example intended for cordova apps, so this really shouldn't be an issue. 

But if you really need it, you could just skip the redirect and use a popup.

```
        Auth.$authWithOAuthPopup(authMethod).then(function(authData) {
          console.dir(authData);
        });
```
